# Generated by Django 3.0.4 on 2020-03-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0002_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent_Checkout_Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_name', models.CharField(max_length=30)),
                ('reagent_taken_out', models.IntegerField()),
            ],
        ),
    ]
