# Generated by Django 3.0.4 on 2020-03-30 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0003_reagent_checkout_database'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reagent_checkout_database',
            old_name='reagent_taken_out',
            new_name='amount_taken',
        ),
    ]
