# Generated by Django 3.0.4 on 2020-03-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0004_auto_20200330_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent_checkout_database',
            name='total_reagent',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
