# Generated by Django 3.0.4 on 2020-03-31 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0005_reagent_checkout_database_total_reagent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagent_checkout_database',
            name='total_reagent',
        ),
    ]
