# Generated by Django 3.0.4 on 2020-04-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0006_remove_reagent_checkout_database_total_reagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hematology_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_name', models.CharField(max_length=30)),
                ('reagent_quantity', models.IntegerField()),
            ],
        ),
    ]
