# Generated by Django 3.0.4 on 2020-04-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0008_chemistry_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Reagent_Checkout_Database',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
