# Generated by Django 3.0.4 on 2020-04-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0009_auto_20200409_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hematology_inventory',
            name='reagent_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
