# Generated by Django 3.0.4 on 2020-04-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0011_auto_20200409_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hematology_inventory',
            name='reagent_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
