# Generated by Django 3.0.4 on 2020-04-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0012_auto_20200410_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coagulation_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_name', models.CharField(max_length=30, unique=True)),
                ('reagent_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Endo_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_name', models.CharField(max_length=30, unique=True)),
                ('reagent_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GasesMetals_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_name', models.CharField(max_length=30, unique=True)),
                ('reagent_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Urines_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_name', models.CharField(max_length=30, unique=True)),
                ('reagent_quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='chemistry_inventory',
            name='reagent_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
