# Generated by Django 3.0.4 on 2020-04-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0013_auto_20200415_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematology_inventory',
            name='par_level',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
