# Generated by Django 3.0.4 on 2020-04-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0014_hematology_inventory_par_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hematology_inventory',
            name='reagent_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
