# Generated by Django 3.0.4 on 2020-04-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0015_auto_20200423_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematology_inventory',
            name='average_use',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
