# Generated by Django 3.0.4 on 2020-04-24 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0016_hematology_inventory_average_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematology_inventory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
