# Generated by Django 3.0.4 on 2020-04-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0018_remove_hematology_inventory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematology_inventory',
            name='updated_act',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
