# Generated by Django 3.0.4 on 2020-04-24 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0019_hematology_inventory_updated_act'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hematology_inventory',
            name='updated_act',
        ),
    ]
