# Generated by Django 3.0.4 on 2020-04-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0020_remove_hematology_inventory_updated_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematology_inventory',
            name='modfied',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
