# Generated by Django 3.0.4 on 2020-04-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0021_hematology_inventory_modfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hematology_inventory',
            name='modfied',
            field=models.DateField(auto_now=True),
        ),
    ]
