# Generated by Django 3.0.4 on 2020-04-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0022_auto_20200424_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hematology_inventory',
            name='modfied',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
