# Generated by Django 3.0.4 on 2020-04-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0024_historicalhematology_inventory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalhematology_inventory',
            table='Hemehistorytabletest2',
        ),
    ]
