# Generated by Django 3.0.4 on 2020-04-29 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0025_auto_20200429_1751'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalhematology_inventory',
            table=None,
        ),
    ]
