# Generated by Django 3.0.4 on 2020-05-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0026_auto_20200429_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hematology_inventory',
            name='average_use',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalhematology_inventory',
            name='average_use',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
