# Generated by Django 3.0.4 on 2020-05-22 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventoryhome', '0027_auto_20200522_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heme_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_name', models.CharField(max_length=30, unique=True)),
                ('reagent_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Heme_Total_Use_Test',
            fields=[
                ('Heme_Test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventoryhome.Heme_Test')),
                ('total_use', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalHeme_Total_Use_Test',
            fields=[
                ('total_use', models.PositiveIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Heme_Test', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventoryhome.Heme_Test')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical heme_ total_ use_ test',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
