# Generated by Django 3.0.4 on 2020-05-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0028_heme_test_heme_total_use_test_historicalheme_total_use_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heme_total_use_test',
            old_name='Heme_Test',
            new_name='reagent_name',
        ),
        migrations.RenameField(
            model_name='historicalheme_total_use_test',
            old_name='Heme_Test',
            new_name='reagent_name',
        ),
    ]
