# Generated by Django 3.0.4 on 2020-05-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0029_auto_20200522_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heme_total_use_test',
            old_name='reagent_name',
            new_name='Heme_Test',
        ),
        migrations.RenameField(
            model_name='historicalheme_total_use_test',
            old_name='reagent_name',
            new_name='Heme_Test',
        ),
    ]
