# Generated by Django 3.0.4 on 2020-05-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0030_auto_20200522_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heme_total_use_test',
            old_name='Heme_Test',
            new_name='heme_test',
        ),
        migrations.RenameField(
            model_name='historicalheme_total_use_test',
            old_name='Heme_Test',
            new_name='heme_test',
        ),
    ]
