# Generated by Django 3.0.4 on 2020-05-22 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0031_auto_20200522_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='heme_total_use_test',
            name='modfied',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicalheme_total_use_test',
            name='modfied',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
