# Generated by Django 3.0.4 on 2020-05-22 22:01

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryhome', '0032_auto_20200522_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heme_total_use_test',
            name='heme_test',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventoryhome.Heme_Test'),
        ),
    ]
